[project]
name = "online-learning-platform"
version = "0.1.0"
description = ""
authors = [
    {name = "Makaka322",email = "chirik2000xd@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-filter (>=25.2,<26.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
